name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    name: Run tests
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.2.2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.6.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Longbow and its testing dependencies
      shell: bash
      run: pip install -e .[testing]

    - name: Run test suite
      shell: bash
      run: pytest --cov longbow --cov-report term-missing --cov-append .

    - name: Report Coverage
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[docs]
    - name: Build docs
      run: cd docs && make

  #pre-commit:
  #  runs-on: ubuntu-24.04
  #  timeout-minutes: 15
  #  steps:
  #  - uses: actions/checkout@v4.2.2
  #  - name: Set up Python
  #    uses: actions/setup-python@v5.6.0
  #    with:
  #      python-version: 3.13
  #  - name: Install python dependencies
  #    run: |
  #      pip install --upgrade pip
  #      pip install -e .[pre-commit,docs,testing]
  #  - name: Run pre-commit
  #    run: |
  #      pre-commit install
  #      pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
